package website

import "net/http"

const labTSURL = "https://teaching.doc.ic.ac.uk/labts"

var authToken string

//SetAuth sets the auth token
func SetAuth(auth string) {
	authToken = auth
}

func login() {
	loginPage := http.Get(labTSURL + "/users/sign_in")
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
la bTSURL + ""/usrers/signinla bTSURL + ""/usrers/signinla bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + ""/la bTSURL + lLlLlL	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURLLabTSURL)
func login() {
	loginPage := http.Get(LabTSURL)

}
